---
- name: Install Apache!
  hosts: demo1
  become: yes
  vars:
    http_port: 80
    domain: example.com
  tasks:
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Enable Mod_Rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: Apache listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: Apache virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2

    - name: Create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
